version: "2.2"

networks:
  net-es:
    driver: bridge
    internal: false

volumes:
  kibana-data:
    external: true
  es-data:
    external: true
  es-plugins:
    external: true

services:
  es:
    image: elasticsearch:${STACK_VERSION}
    container_name: es
    healthcheck:
      test: ["CMD-SHELL","curl localhost:9200 | grep -i 'You Know, for Search'"]
      interval: 20s
      timeout: 5s
      retries: 2
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    #      - clster.name=es-cluster
    volumes:
      - es-data:/usr/share/elasticsearch/data
      - es-plugins:/usr/share/elasticsearch/plugins
      - ./logs:/usr/share/elasticsearch/logs
    tty: true
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - net-es
    restart: on-failure
    hostname: es
  kibana:
    container_name: kibana
    image: kibana:${STACK_VERSION}
    volumes:
      - kibana-data:/user/share/kibana/data
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
    tty: true
    restart: on-failure
    depends_on:
      es:
        condition: service_healthy
    ports:
      - 5601:5601
    networks:
      - net-es
    hostname: kibana
