#name: ${PROJECT_NAME:-sentinel}
version: "3.3"

services:
  sentinel:
    container_name: sentinel
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SENTINEL_VERSION=1.8.6
    image: sentinel-dashboard
    env_file:
      - sentinel.env
    ports:
      - "8080:8080"





