version: "3.3"
services:
  nacos:
    image: nacos/nacos-server
    container_name: nacos
    env_file:
      - ./nacos.env
    volumes:
      - ./logs/:/home/nacos/logs
    ports:
      - 8848:8848
      - 9848:9848
  seata-server:
    image: seataio/seata-server
    container_name: seata-server
    hostname: seata-server
    ports:
      - "8091:8091"
      - "7091:7091"
    volumes:
      - ./resources:/seata-server/resources
    environment:
      - SEATA_IP=8.130.131.185 #The registry ip in nacos.
      - SEATA_PORT=8091
      - STORE_MODE=file
      - JVM_XMS=512m
      - JVM_XMX=512m
    depends_on:
      - nacos




