version: "3.3"

networks:
  net-es:
    driver: bridge
    internal: false

volumes:
  kibana-data:
    external: true
  es-data:
    external: true
  es-plugins:
    external: true

services:
  es:
    image: elasticsearch:8.6.2
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
#      - clster.name=es-cluster
    volumes:
      - es-data:/usr/share/elasticsearch/data
      - es-plugins:/usr/share/elasticsearch/plugins
    privileged: true
    tty: true
#    user: root
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - net-es
    restart: on-failure
    hostname: es
  kibana:
    image: kibana:8.6.2
    volumes:
      - kibana-data:/user/share/kibana/data
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
    privileged: true
    tty: true
#    user: root
    restart: on-failure
    depends_on:
      - es
    ports:
      - 5601:5601
    networks:
      - net-es
    hostname: kibana
