version: "2.2"
services:
  nacos:
    image: nacos/nacos-server
    container_name: nacos
    healthcheck:
      test: ["CMD-SHELL","curl -X GET http://nacos:8848/nacos/v2/ns/operator/metrics | grep -i up"]
      interval: 20s
      timeout: 10s
      retries: 2
      # start_period: 15s
    env_file:
      - ./nacos.env
    volumes:
      - ./logs/:/home/nacos/logs
    ports:
      - 8848:8848
      - 9848:9848
  seata-server:
    image: seataio/seata-server
    container_name: seata-server
    hostname: seata-server
    ports:
      - "8091:8091"
      - "7091:7091"
    volumes:
      - ./resources:/seata-server/resources
    environment:
      - SEATA_IP=8.130.131.185
      - SEATA_PORT=8091
      - STORE_MODE=db
      - JVM_XMS=512m
      - JVM_XMX=512m
    depends_on:
      nacos:
        condition: service_healthy
    restart: 
      on-failure




